name: GitHub Snake Game

on:
  schedule:
    - cron: "0 0 * * *"
    - cron: "0 12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "dist/**"

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Cache Generated Files
        uses: actions/cache@v3
        with:
          path: ./dist
          key: ${{ runner.os }}-snake-cache
          restore-keys: |
            ${{ runner.os }}-snake-cache

      - name: Generate GitHub Contributions Snake Animations
        uses: Platane/snk@v3
        with:
          github_user_name: "Tahsinnazar"
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=yellow&color_dots=#ffcc00,#ffaa00,#ff8800,#ff5500,#ff2200
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git User
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Ensure Output Branch Exists
        run: |
          git fetch origin output || true
          if ! git show-ref --verify --quiet refs/remotes/origin/output; then
            echo "Creating output branch..."
            git checkout --orphan output
            git rm -rf .
            git commit --allow-empty -m "Initial output branch"
            git push origin output
          fi

      - name: Deploy to Output Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update snake animation [skip ci]"


